# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python checks

on:
  push:
    branches: [ python2 ]
  pull_request:
    branches: [ python2 ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit
        pip install -r requirements.txt
    - name: Lint with flake8
      run: flake8
    - name: Check code security with bandit
      run: bandit -ll -r .
    - name: Test run
      run: |
        set -e
        python sonic-pi-tool.py --help
        ./sonic-pi-tool.py check || true
        ./sonic-pi-tool.py --verbose eval play 60
        ./sonic-pi-tool.py --verbose osc /foo '"bar"' baz 123 3.14
        ./sonic-pi-tool.py stop
        ./sonic-pi-tool.py shutdown
